# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo apt install libboost-math-dev cmake g++ python3-flake8 python3-pytest -y
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Unit Test for Python
      run: |
        # stop the build if there are Python syntax errors or undefined names
        cd ciphey
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        # python3 -m unittest discover
